package eu.ha3.katastrophe.monad.ws

enum class Err(val status: Int) {
    AUTHORIZATION_HEADER_MISSING(401),
    TOO_MANY_AUTHORIZATION_HEADERS(400),
    AUTHORIZATION_HEADER_HAS_TRAILING_WHITESPACE(400),
    NOT_AUTHENTICATED(401),
    NOT_BEARER_TOKEN(400),
    TOKEN_HAS_TRAILING_WHITESPACE(400),
    PARAMETER_MISSING_ID(400),
    UNKNOWN_ERROR_WITH_MESSAGE_REPOSITORY(500),
    DATE_FORMAT_IS_INVALID(400),
    PARAMETER_MISSING_BEGIN_DATE(400),
    PARAMETER_MISSING_END_DATE(400)
}